// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwQ8mZtG_P1f7ru2Z8rw6O9j-6X3tJ-mY',
    appId: '1:1068052240875:web:46302a48bd87482c5ba1ae',
    messagingSenderId: '1068052240875',
    projectId: 'fitnessapp-15477',
    authDomain: 'fitnessapp-15477.firebaseapp.com',
    storageBucket: 'fitnessapp-15477.appspot.com',
    measurementId: 'G-DEL30C21M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR45SpmSKwYvoqp110SIEPCdStR1mZ_NU',
    appId: '1:1068052240875:android:f15cf153b0934c515ba1ae',
    messagingSenderId: '1068052240875',
    projectId: 'fitnessapp-15477',
    storageBucket: 'fitnessapp-15477.appspot.com',
  );
}
